---
title: "Exploratory Analysis for MoTR Reading Data"
output: html_notebook
---

```{r}
shhh <- suppressPackageStartupMessages # It's a library, so shhh!

shhh(library( mgcv ))
shhh(library(dplyr))
shhh(library(ggplot2))
shhh(library(lme4))
shhh(library(tidymv))
shhh(library(gamlss))
shhh(library(gsubfn))
shhh(library(lmerTest))
shhh(library(tidyverse))
shhh(library(boot))
shhh(library(rsample))
shhh(library(plotrix))
shhh(library(ggrepel))
shhh(library(mgcv))
shhh(library(brms))
shhh(library(bayesplot))
shhh(library(tidyr))
shhh(library(car))
shhh(library(coda))
shhh(library(gridExtra))
shhh(library(posterior))

theme_set(theme_bw())
options(digits=4)
options(scipen=999)
set.seed(444)

```


# Read in MoTR Data

```{r}

# The path to the data
data_path = "./data/"
data_names = list.files(data_path)

# Read in the data from each participant and add to the data frame
motr_df = data.frame()
for(name in data_names){
  subj = gsub("reader_", "", gsub("_reading_measures.csv", "", name))
  temp_df = read.csv(paste0(data_path, "/", name)) %>% mutate(subj_id = subj)
  motr_df = rbind(motr_df, temp_df)
}


# Turn the data into a tidy dataframe and clean the data
clean_df = motr_df %>%
  gather(measure, value, 17:23) %>%
  mutate(tgt_zero = if_else(measure %in% c("first_duration", "gaze_duration", "go_past_time", "right_bounded_rt", "total_duration") & value == 0, F, T)) %>%
  filter(tgt_zero != F) %>%
  dplyr::select(-tgt_zero) %>%
  # CHANGE: filter by over-all accuracy
  filter(correctness == 1 )

motr_df

```




```{r}

# Run a lmer model with a three-way interaction between gender matching, stimulus type and gender of noun
model = clean_df %>% filter(word_nr == 3) %>%
  filter(measure == "go_past_time") %>%
  filter(type %in% c("stim_adj", "stim_pred_adj", "stim_verb")) %>%
  mutate(gender_match = if_else(gender_match == "Mis", 1, -1),
         target_gender = if_else(target_gender == "M", 1, -1),
         item_id = as.factor(item_id)) %>%
  lmer(value ~ gender_match * type * target_gender + (1 | item_id ) + (1 | subj_id ), data = ., REML=F)

summary(model)

```


```{r}

# Run a model for each category in the data (for each stimulus type, measurement and target gender)

stim_types = c("stim_adj", "stim_pred_adj", "stim_verb")
measure_types = c("gaze_duration", "go_past_time", "total_duration")
target_genders = c("M", "F")

stats_df = data.frame()
for(stim in stim_types){
  for (meas in measure_types){
    for(gend in target_genders){
    
      model = clean_df %>% filter(type == stim, measure == meas, target_gender == gend, word_nr == 3) %>%
        mutate(gender_match = if_else(gender_match == "Mis", 1, -1),
               item_id = as.factor(item_id)) %>%
        lmer(value ~ gender_match + (gender_match || item_id ) + (gender_match || subj_id ), data = ., REML=F)
      
      temp_results = data.frame(stim = stim, target_gender = gend, measure = meas, beta = summary(model)$coefficients[2], pval = summary(model)$coefficients[10])
  
      stats_df = rbind(stats_df, temp_results)
    
    }
  }
}

stats_df = stats_df %>%
  mutate(sig = if_else(pval < 0.05 & beta > 0, "SIG", ""))

stats_df

```





```{r}
# Create an aggregate DF with mean and 95% CIs for each condition and sentence region

agg_df = clean_df %>%
  group_by(type, gender_match, word_nr, measure, target_gender) %>%
    summarise(
      m = mean(value),
      s = std.error(value),
      lower = m - 1.96 * s,
      upper = m + 1.96 * s
    ) %>%
  ungroup()

agg_df 

```

```{r}

# Plot the reading times in each region broken down by stimulus type, reading measure and target gender

for (stim in c("stim_adj", "stim_pred_adj", "stim_verb")) {

agg_df %>%
  filter(type == stim) %>%
  filter(measure %in% c("gaze_duration", "go_past_time", "total_duration")) %>%
  ggplot(aes(x=word_nr, y=m, color = gender_match)) +
    geom_rect(aes(xmin=2.5, xmax=3.5, ymin=200, ymax =850), color = "green", fill = NA) +
    geom_point() +
    geom_errorbar(aes(ymin=lower, ymax=upper), width = 0.2) +
    geom_line() +
    facet_grid(measure~target_gender) +
    ggtitle(paste0("Region by region plot for ", stim)) +
    ylab("Reading time in ms") +
    xlab("Word Number") +
  coord_cartesian(ylim=c(0, 900)) +
  theme(
    legend.position = "bottom"
  )

ggsave(paste0("./images/overview_rts_",stim,".pdf"), device="pdf", height=8, width=8)

}


```

```{r}

# Plot the proportion of regressions in each region

agg_df %>%
  filter(type %in% c("stim_adj", "stim_pred_adj", "stim_verb")) %>%
  filter( measure %in% c("FPReg")) %>%
  ggplot(aes(x=word_nr, y=m, color = gender_match)) +
    geom_rect(aes(xmin=2.5, xmax=3.5, ymin=0, ymax =0.2 ), color = "green", fill = NA) +
    geom_point() +
    geom_errorbar(aes(ymin=lower, ymax=upper), width=0.2) +
    geom_line() +
    facet_grid(target_gender~type) +
  coord_cartesian(ylim=c(0, 0.25)) +
  theme(
    legend.position = "bottom"
  )

ggsave("./images/regression.pdf", device="pdf", height=4, width=8)


```